---
driver:
  name: gogetkitchen

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  install_strategy: once

transport:
  name: sftp
  ssh_key: <%= Dir.home + '/.ssh/id_rsa' %>

verifier:
  name: inspec

platforms:
  - name: def-lxc
    driver:
      provider: lxd
      template: ubuntu-16.04-chef

suites:
  - name: nrm
    data_bags_path: data_bags
    verifier:
      inspec_tests:
        - test/integration/default
